function createfigure()
X1 = [6, 8, 10]
X2 = [2, 4, 6, 8, 10]

Y1 = [3429 3197 3060]
E1 = [150.58 132.86 117.06]

Y2 = [430.6 274.6 211.2 172.4 173.4]
E2 = [49.49 41.72 31.91 15.70 6.58]

%  Auto-generated by MATLAB on 03-May-2014 19:59:12

% Create figure
figure1 = figure('PaperSize',[20.98404194812 29.67743169791]);

% Create axes
axes1 = axes('Parent',figure1,'FontSize',14);
box(axes1,'on');
hold(axes1,'all');

% Create errorbar
errorbar(X1,Y1,E1,'LineWidth',1,'DisplayName','PageRank',...
    'Color',[0 0 1],...
    'Parent',axes1);

hold on

errorbar(X2,Y2,E2,'LineWidth',1,'DisplayName','Reverse Link Graph',...
    'Color',[1 0 0],...
    'Parent',axes1);

% Create xlabel
xlabel({'Number of Machines'},'FontSize',14);

% Create ylabel
ylabel({'Average Runtime (Seconds)'},'FontSize',14);

% Create legend
legend(axes1,'show');

