function createfigure()
%CREATEFIGURE(X1,Y1,E1)
%  X1:  errorbar x
%  Y1:  errorbar y
%  E1:  errorbar e

Y1 = [430.6000 274.6000 211.2 172.4000 173.4]
X1 = [2, 4, 6, 8, 10]
E1 = [49.49, 41.72, 31.91 15.7 6.58]

%  Auto-generated by MATLAB on 03-May-2014 19:59:12

% Create figure
figure1 = figure('PaperSize',[20.98404194812 29.67743169791]);

% Create axes
axes1 = axes('Parent',figure1,'FontSize',14);
box(axes1,'on');
hold(axes1,'all');

% Create errorbar
errorbar(X1,Y1,E1,'LineWidth',1,'DisplayName','Average Runtime',...
    'Color',[0 0 1],...
    'Parent',axes1);

% Create xlabel
xlabel({'Number of Machines'},'FontSize',14);

% Create ylabel
ylabel({'Average Runtime (Seconds)'},'FontSize',14);

% Create legend
legend(axes1,'show');

