function createfigure()
X1 = [2, 4, 6, 8, 10]

Y1 = [144.2 92.2 72 62.2 59.4]
E1 = [1.92 2.04 1.87 3.63 3.28]

Y2 = [430.6 274.6 211.2 172.4 173.4]
E2 = [49.49 41.72 31.91 15.70 6.58]

%  Auto-generated by MATLAB on 03-May-2014 19:59:12

% Create figure
figure1 = figure('PaperSize',[20.98404194812 29.67743169791]);

% Create axes
axes1 = axes('Parent',figure1,'FontSize',14);
box(axes1,'on');
hold(axes1,'all');

% Create errorbar
errorbar(X1,Y1,E1,'LineWidth',1,'DisplayName','Average Runtime',...
    'Color',[0 0 1],...
    'Parent',axes1);

hold on

errorbar(X1,Y2,E2,'LineWidth',1,'DisplayName','Average Runtime',...
    'Color',[0 0 1],...
    'Parent',axes1);

% Create xlabel
xlabel({'Number of Machines'},'FontSize',14);

% Create ylabel
ylabel({'Average Runtime (Seconds)'},'FontSize',14);

% Create legend
legend(axes1,'show');

